# The graph table configures how the dependency graph is constructed and thus
# which crates the checks are performed against
[graph]

targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
]

all-features = true

[advisories]
version = 2
yanked  = "deny"

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "Unicode-DFS-2016",
    "ISC",
]
confidence-threshold = 0.93

[bans]
multiple-versions          = "deny"
wildcards                  = "deny"
highlight                  = "all"
workspace-default-features = "warn"
external-default-features  = "allow"
allow                      = []
deny                       = []

#[[bans.features]]

skip = []

skip-tree = []

[sources]
unknown-registry  = "warn"
unknown-git       = "warn"
required-git-spec = "tag"

allow-registry = ["https://github.com/rust-lang/crates.io-index"]
